SELECT TITLE,AUTHOR FROM super UNION SELECT TITLE,AUTHOR FROM bestseller
SELECT * FROM `super` WHERE PRICE>400
SELECT AVG(PRICE) FROM super
SELECT * FROM `super`
SELECT COUNT(*) FROM super
SELECT TITLE AS Booktitle, AUTHOR AS Writtenby FROM super
​